# name: Deploy

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Install packages
#         run: npm install
#       - name: Build project
#         run: npm run-script build
#       - uses: akhileshns/heroku-deploy@v3.11.10 # This is the action
#         with:
#           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#           heroku_app_name: "rubric-front-end" #Must be unique in Heroku
#           heroku_email: ${{secrets.HEROKU_EMAIL}}
